[tools]
aws-cli = "latest"
bat = "latest"
bun = "latest"
cosign = "latest"
chezmoi = "latest"
cilium-cli = "latest"
delta = "latest"
difftastic = "latest"
fzf = "latest"
ghq = "latest"
kubeseal = "0.27.1"
lsd = "latest"
"ubi:cantino/mcfly" = "latest"
neovim = "latest"
node = "24"
"npm:pnpm" = "latest-10"
# onefetch>=2.24.0 requires glibc>=2.38
"ubi:o2sh/onefetch" = "2.23.1"
rclone = "latest"
ripgrep = "latest"
starship = "latest"
tfenv = "latest"
usage = "latest"
yq = "latest"
