[tools]
aws-cli = "latest"
bat = "latest"
cosign = "latest"
chezmoi = "latest"
cilium-cli = "latest"
delta = "latest"
difftastic = "latest"
fzf = "latest"
ghq = "latest"
kubeseal = "0.27.1"
lsd = "latest"
"ubi:cantino/mcfly" = "latest"
neovim = "latest"
node = "22"
"npm:pnpm" = "latest-10"
# onefetch>=2.24.0 requires glibc>=2.38
"ubi:o2sh/onefetch" = "2.23.1"
rclone = "latest"
ripgrep = "latest"
starship = "latest"
tfenv = "latest"
usage = "latest"
yq = "latest"

[settings]
# Idiomatic version files like [...]/.node-version are currently enabled by default. However, this will change in mise 2025.10.0 to instead default to disabled.
# You can remove this warning by explicitly enabling idiomatic version files for node with:
#     mise settings add idiomatic_version_file_enable_tools node
# You can disable idiomatic version files with:
#     mise settings add idiomatic_version_file_enable_tools "[]"
# See https://github.com/jdx/mise/discussions/4345 for more information.
idiomatic_version_file_enable_tools = []
